name: Manage VMs

on:
  push:
    branches:
      - main

jobs:
  create-vm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Initialize Terraform (Create VM)
        run: terraform init modules/create_vm

      - name: Plan Terraform (Create VM)
        run: terraform plan modules/create_vm

      - name: Apply Terraform (Create VM)
        run: terraform apply -auto-approve modules/create_vm

      - name: Output VM details
        run: |
          echo "VM Public IP: ${{ steps.apply.outputs.instance_public_ip }}"

  delete-vm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Initialize Terraform (Delete VM)
        run: terraform init modules/delete_vm

      - name: Plan Terraform (Delete VM)
        run: terraform plan modules/delete_vm

      - name: Destroy Terraform Resources (Delete VM)
        run: terraform destroy -auto-approve modules/delete_vm

